polls/urls.py
from django.conf.urls import url
from . import views

app_name='polls'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.choices, name='choices'),
    url(r'^(?P<question_id>[0-9]+)/selected/$', views.selected, name='selected'),
]

 

pollsapp/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url('^polls/', include('polls.urls')),
    url('^admin/', admin.site.urls),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    is_selected = models.BooleanField(default=False)
        
    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question,Choice

def index(request):
    all_questions = Question.objects.all() 
    context={ 'all_questions' : all_questions, }
    return render(request, 'polls/index.html' , context) 

def choices(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/choices.html', { 'question': question })


def selected(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    for choice in question.choice_set.all():
        choice.is_selected=False
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice']) 
    except (KeyError,Choice.DoesNotExist):
        return render(request, 'polls/choices.html', { 
        'question': question,
        'error_message': "You did not select a valid choice.",    
        })
    else:
        selected_choice.is_selected=True
        for choice in question.choice_set.all():
            if choice.id != selected_choice.id:
                choice.is_selected=False
                choice.save()

        selected_choice.votes+=1

        selected_choice.save()
        return render(request , 'polls/choices.html', { 'question' : question })

polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <title>{% block title %}Polls{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Cabin|Open+Sans:600" rel="stylesheet">  
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'polls:index' %}">Polls</a>
                </div>
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">
                        <li class="{% block questions_active %}{% endblock %}">
                            <a href="{% url 'polls:index' %}">
                                <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>&nbsp;
                            Questions
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span>&nbsp;
                            Votes
                            </a>
                        </li>
                    </ul>                    
                    <form class="navbar-form navbar-left" role="search" method="get" action="#">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                            Add Question
                            </a>
                        </li>
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                            Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

polls/templates/polls/choices.html
{% extends 'polls/base.html' %}
{% block title %}Question Choices{% endblock %}
{% block body %}
<div class="container jumbotron">
    <h1>{{ question.question_text }} </h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:selected' question.id %}" method="post" class="list-group">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}" class="list-group-item" id="option">
                {{ choice.choice_text }}
                <span class="badge"><strong> Votes = </strong> {{ choice.votes }}</span>
            </label><br>
        {% endfor %}
        <input type="submit" value="Vote" >
    </form>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block body %}
    {% if all_questions  %}
    <div class="container jumbotron">    
        <h1>Questions:</h1>    
        <ol>
            {% for question in all_questions %}
            <li class='question'><a href="{% url 'polls:choices' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ol>
    </div>
    {% else %}
        <h2>You don't have any questions</h2>
    {% endif %}
{% endblock %}